import { type ReactElement, useEffect, useRef, useState } from "react";
import type { MessageKey } from "../i18n.js";
import type { ServiceLibrary, WorkBlueprint } from "../libraryTypes.js";
import { libraryRefKey } from "../libraryTypes.js";
import { blueprintDraftErrors, nextBlueprintId, newBlueprintTask, sameText, sameLines, textMismatch, linesMismatch, type BlueprintDraft, type BlueprintDraftError } from "../libraryAuthoringState.js";

// A record saved under the old two-field editor can hold two different texts. Both are shown
// as they were stored and one has to be chosen; nothing here translates or merges them.
export function LegacyTextChoice({ en, ru, text, onChoose }: { en: string; ru: string; text: (key: MessageKey) => string; onChoose: (value: string) => void }): ReactElement {
  return <div className="legacy-text-conflict"><p className="small-copy" role="alert">{text("library_legacy_conflict")}</p>
    {([["English", en], ["Русский", ru]] as const).map(([label, value]) => <div className="legacy-text-option" key={label}><p className="small-copy">{label}</p><p className="legacy-text-value">{value}</p><button className="button button-secondary" type="button" onClick={() => onChoose(value)}>{text("library_legacy_use")}</button></div>)}
  </div>;
}
export function BlueprintDefinitionEditor({ draft, onChange, catalog, plans, text, locked, onSave, onClose }: { draft: BlueprintDraft; onChange: (draft: BlueprintDraft) => void; catalog: ServiceLibrary; plans: readonly WorkBlueprint[]; text: (key: MessageKey) => string; locked: boolean; onSave: () => void; onClose: () => void }): ReactElement {
  const form = useRef<HTMLFormElement>(null);
  useEffect(() => { if (!form.current?.closest("[hidden]")) { form.current?.scrollIntoView({ block: "start" }); form.current?.querySelector<HTMLInputElement>("input:not(:disabled)")?.focus({ preventScroll: true }); } }, []);
  const [errors, setErrors] = useState<BlueprintDraftError[]>([]);
  const update = (next: BlueprintDraft): void => { onChange(next); setErrors([]); };
  const slots = draft.slots;
  const changeSlot = (index: number, next: BlueprintDraft["slots"][number]): void => update({ ...draft, slots: slots.map((slot, i) => i === index ? next : slot) });
  const changeTask = (index: number, next: BlueprintDraft["tasks"][number]): void => update({ ...draft, tasks: draft.tasks.map((task, i) => i === index ? next : task) });
  const roleOptions = [...catalog.roles.map((role) => ({ ref: role.ref, name: role.name })), ...draft.retainedRoles.filter((ref, index, refs) => refs.findIndex((item) => libraryRefKey(item) === libraryRefKey(ref)) === index && !catalog.roles.some((role) => libraryRefKey(role.ref) === libraryRefKey(ref))).map((ref) => ({ ref, name: ref.id }))];
  return <form ref={form} className="library-editor blueprint-definition-editor" onSubmit={(event) => { event.preventDefault(); if (locked) return; const found = blueprintDraftErrors(draft, catalog, plans); setErrors(found); if (!found.length) onSave(); }} noValidate><div className="composer-heading"><h3>{text(draft.expectedVersion ? "library_edit_custom" : draft.forkRef ? "library_blueprint_copy" : "library_new_blueprint")}</h3><button type="button" className="button button-secondary" disabled={locked} onClick={onClose}>{text("shell_close")}</button></div><p className="small-copy">{text("library_blueprint_definition_help")}</p>
    <fieldset disabled={locked}><label>{text("library_id")}<input autoFocus value={draft.id} maxLength={64} disabled={draft.expectedVersion !== null} onChange={(event) => update({ ...draft, id: event.currentTarget.value })} /></label><p className="small-copy">{text("library_text_single_help")}</p>
    <label>{text("library_name")}<input value={draft.name.en} maxLength={200} disabled={textMismatch(draft.name)} onChange={(event) => update({ ...draft, name: sameText(event.currentTarget.value) })} /></label>{textMismatch(draft.name) ? <LegacyTextChoice en={draft.name.en} ru={draft.name.ru} text={text} onChoose={(value) => update({ ...draft, name: sameText(value) })} /> : null}
    <label>{text("library_description")}<textarea rows={3} value={draft.description.en} disabled={textMismatch(draft.description)} onChange={(event) => update({ ...draft, description: sameText(event.currentTarget.value) })} /></label>{textMismatch(draft.description) ? <LegacyTextChoice en={draft.description.en} ru={draft.description.ru} text={text} onChoose={(value) => update({ ...draft, description: sameText(value) })} /> : null}
    <h4>{text("library_blueprint_slots")}</h4>{slots.map((slot, index) => <section className="blueprint-definition-row" key={slot.id}><h5>{text("library_blueprint_slot")} {index + 1}</h5><p className="small-copy"><code>{slot.id}</code></p><label>{text("role_name")}<input value={slot.name} maxLength={200} onChange={(event) => changeSlot(index, { ...slot, name: event.currentTarget.value })} /></label><label>{text("library_specialization")}<select value={slot.roleRef ? libraryRefKey(slot.roleRef) : ""} onChange={(event) => changeSlot(index, { ...slot, roleRef: roleOptions.find((role) => libraryRefKey(role.ref) === event.currentTarget.value)?.ref ?? null })}><option value="">{text("library_no_specialization")}</option>{roleOptions.map((role) => <option key={libraryRefKey(role.ref)} value={libraryRefKey(role.ref)}>{role.name} · {role.ref.version.slice(0, 8)}</option>)}</select></label><button className="notice-link" type="button" disabled={slots.length === 1 || draft.tasks.some((task) => task.slot_id === slot.id)} onClick={() => update({ ...draft, slots: slots.filter((_, i) => i !== index) })}>{text("library_remove_slot")}</button></section>)}<button className="button button-secondary" type="button" disabled={slots.length >= 32} onClick={() => update({ ...draft, slots: [...slots, { id: nextBlueprintId("role", slots), name: "", roleRef: null }] })}>{text("library_add_slot")}</button>
    <h4>{text("library_blueprint_tasks")}</h4>{draft.tasks.map((task, index) => <section className="blueprint-definition-row" key={task.id}><h5>{text("library_blueprint_task")} {index + 1}</h5><p className="small-copy"><code>{task.id}</code></p><label>{text("library_name")}<input maxLength={200} value={task.title.en} disabled={textMismatch(task.title)} onChange={(event) => changeTask(index, { ...task, title: sameText(event.currentTarget.value) })} /></label>{textMismatch(task.title) ? <LegacyTextChoice en={task.title.en} ru={task.title.ru} text={text} onChoose={(value) => changeTask(index, { ...task, title: sameText(value) })} /> : null}<label>{text("library_description")}<textarea rows={3} value={task.description.en} disabled={textMismatch(task.description)} onChange={(event) => changeTask(index, { ...task, description: sameText(event.currentTarget.value) })} /></label>{textMismatch(task.description) ? <LegacyTextChoice en={task.description.en} ru={task.description.ru} text={text} onChoose={(value) => changeTask(index, { ...task, description: sameText(value) })} /> : null}<label>{text("library_task_criteria")}<textarea rows={3} value={task.acceptance_criteria.en.join("\n")} disabled={linesMismatch(task.acceptance_criteria)} onChange={(event) => changeTask(index, { ...task, acceptance_criteria: sameLines(event.currentTarget.value.split("\n")) })} /></label>{linesMismatch(task.acceptance_criteria) ? <LegacyTextChoice en={task.acceptance_criteria.en.join("\n")} ru={task.acceptance_criteria.ru.join("\n")} text={text} onChoose={(value) => changeTask(index, { ...task, acceptance_criteria: sameLines(value.split("\n")) })} /> : null}<label>{text("library_blueprint_slot")}<select value={task.slot_id} onChange={(event) => changeTask(index, { ...task, slot_id: event.currentTarget.value })}>{slots.map((slot) => <option key={slot.id} value={slot.id}>{slot.name || slot.id}</option>)}</select></label><fieldset className="blueprint-dependencies"><legend>{text("library_task_dependencies")}</legend>{draft.tasks.filter((candidate) => candidate.id !== task.id).map((candidate) => <label key={candidate.id}><input type="checkbox" checked={task.depends_on.includes(candidate.id)} onChange={(event) => changeTask(index, { ...task, depends_on: event.currentTarget.checked ? [...task.depends_on, candidate.id] : task.depends_on.filter((id) => id !== candidate.id) })} />{candidate.title.en || candidate.id}</label>)}</fieldset><button className="notice-link" type="button" disabled={draft.tasks.length === 1 || draft.tasks.some((candidate) => candidate.depends_on.includes(task.id))} onClick={() => update({ ...draft, tasks: draft.tasks.filter((_, i) => i !== index) })}>{text("library_remove_task")}</button></section>)}<button className="button button-secondary" type="button" disabled={draft.tasks.length >= 64} onClick={() => update({ ...draft, tasks: [...draft.tasks, newBlueprintTask(nextBlueprintId("task", draft.tasks), slots[0].id)] })}>{text("library_add_task")}</button>
    {errors.length ? <ul className="field-error" role="alert">{errors.map((error) => <li key={error}>{text(error === "legacy" ? "library_legacy_required" : `library_blueprint_error_${error}`)}</li>)}</ul> : null}<p className="small-copy">{text("library_blueprint_save_help")}</p><button className="button button-primary" type="submit">{text("library_save_version")}</button></fieldset></form>;
}
