import type { Locale } from "./i18n.js";
const en = {
  expired: "Attachments expired before sending. Your files are uploading again; send once they are ready.",
  history: "Recent conversations", current: "Current conversation", closed: "Closed conversation", closedNotice: "This conversation is closed. Select the current conversation to write a message.",
  historyPartial: "Showing recent messages. Earlier messages are available above.", historyLimited: "Showing the latest 2,000 loaded messages. Older messages remain recorded but are outside this view.", olderError: "Earlier messages could not be loaded. Retry Show earlier messages.",
  conversation: "Conversation", for: "Conversation for", close: "Close", refresh: "Refresh", loading: "Loading conversation…", empty: "No messages yet.", readonly: "You can read this conversation. Sending is unavailable in this workspace.", unavailable: "The conversation could not be refreshed. Your draft is kept here.",
  project: "Messages are for this project's agents. Current and future runs can fetch them; posting does not start a run.", task: "Messages are for agents working on this task. Posting does not start a run.", agent: "Messages are for this agent's runs. Posting does not start a run.",
  message: "Message", send: "Send message", sending: "Recording message…", retrySend: "Retry the same send", uncertain: "The send result is unknown. Retry sends the same message with the same identity. Editing is paused until it is confirmed.", recordedNotice: "Message recorded. Delivery status updates as agents fetch, acknowledge, and reply.", revision: "The conversation changed before this send. Review the refreshed messages and send again.", validation: "The message was not recorded. Check the text and attachments before sending again.",
  attach: "Add images or files", limits: "Up to 10 PNG/JPEG images and 10 files, 15 MB each. Drafts stay in this open app across projects; reloading the page clears them.", bytes: "Message text must be no more than 64,000 UTF-8 bytes.",
  size: "Each attachment must contain 1 byte to 15 MB.", format: "Images must use PNG or JPEG format.", count: "Keep at most 10 images and 10 files per message.", filename: "Use a filename of up to 180 UTF-8 bytes without paths or control characters.",
  uploadRejected: "This file was rejected. Remove it and choose a valid file.", queuedUpload: "Waiting to upload", uploading: "Uploading", ready: "Uploaded", uploadUncertain: "Upload not confirmed. Retry to recover it before sending or removing.", removing: "Removing", removeUncertain: "Removal not confirmed. Retry removal before sending.", retry: "Retry upload", remove: "Remove", retryRemove: "Retry removal", download: "Download", downloadError: "This attachment could not be downloaded.", previewError: "Image preview unavailable.",
  recorded: "Recorded", queued: "Queued for a run", fetched: "Fetched by a run", acknowledged: "Reading acknowledged", answered: "Reply recorded", readConfirmed: "Reading explicitly acknowledged", noRead: "Reading has not been acknowledged", operator: "You", unknown: "Unknown author", agentAuthor: "Agent", reply: "Reply", replying: "Replying to a message", cancelReply: "Cancel reply", earlier: "Show earlier messages", delivery: "Delivery details"
};
const ru: typeof en = {
  expired: "Срок хранения вложений истёк до отправки. Файлы загружаются заново; отправьте сообщение, когда они будут готовы.",
  history: "Недавние обсуждения", current: "Текущее обсуждение", closed: "Закрытое обсуждение", closedNotice: "Обсуждение закрыто. Выберите текущее обсуждение, чтобы написать сообщение.",
  historyPartial: "Показаны последние сообщения. Предыдущие можно загрузить выше.", historyLimited: "Показаны последние 2000 загруженных сообщений. Более ранние сохранены, но не входят в этот просмотр.", olderError: "Не удалось загрузить предыдущие сообщения. Повторите загрузку кнопкой выше.",
  conversation: "Обсуждение", for: "Обсуждение:", close: "Закрыть", refresh: "Обновить", loading: "Загрузка обсуждения…", empty: "Сообщений пока нет.", readonly: "Вы можете читать обсуждение. Отправка в этом пространстве недоступна.", unavailable: "Не удалось обновить обсуждение. Черновик сохранён здесь.",
  project: "Сообщения адресованы агентам проекта. Текущие и будущие запуски могут получить их; отправка не запускает агента.", task: "Сообщения адресованы агентам, работающим над этой задачей. Отправка не запускает агента.", agent: "Сообщения адресованы запускам этого агента. Отправка не запускает агента.",
  message: "Сообщение", send: "Отправить сообщение", sending: "Запись сообщения…", retrySend: "Повторить ту же отправку", uncertain: "Результат отправки неизвестен. Повтор использует то же сообщение с тем же идентификатором. До подтверждения редактирование приостановлено.", recordedNotice: "Сообщение записано. Статус обновится, когда агенты получат его, подтвердят чтение и ответят.", revision: "Обсуждение изменилось до отправки. Просмотрите обновлённые сообщения и отправьте ещё раз.", validation: "Сообщение не записано. Проверьте текст и вложения перед повторной отправкой.",
  attach: "Добавить изображения или файлы", limits: "До 10 изображений PNG/JPEG и 10 файлов по 15 МБ. Черновики остаются в открытом приложении при смене проекта; перезагрузка страницы очищает их.", bytes: "Текст сообщения — не более 64 000 байт UTF-8.",
  size: "Размер каждого вложения — от 1 байта до 15 МБ.", format: "Для изображений поддерживаются PNG и JPEG.", count: "В сообщении может быть не более 10 изображений и 10 файлов.", filename: "Имя файла — до 180 байт UTF-8, без путей и управляющих символов.",
  uploadRejected: "Файл отклонён. Удалите его и выберите подходящий файл.", queuedUpload: "Ожидает загрузки", uploading: "Загрузка", ready: "Загружено", uploadUncertain: "Загрузка не подтверждена. Повторите её перед отправкой или удалением.", removing: "Удаление", removeUncertain: "Удаление не подтверждено. Повторите удаление перед отправкой.", retry: "Повторить загрузку", remove: "Удалить", retryRemove: "Повторить удаление", download: "Скачать", downloadError: "Не удалось скачать вложение.", previewError: "Предпросмотр изображения недоступен.",
  recorded: "Записано", queued: "В очереди для запуска", fetched: "Получено запуском", acknowledged: "Чтение подтверждено", answered: "Ответ записан", readConfirmed: "Чтение явно подтверждено", noRead: "Чтение не подтверждено", operator: "Вы", unknown: "Неизвестный автор", agentAuthor: "Агент", reply: "Ответить", replying: "Ответ на сообщение", cancelReply: "Отменить ответ", earlier: "Показать предыдущие сообщения", delivery: "Подробности доставки"
};
export function conversationText(locale: Locale): typeof en { return locale === "ru" ? ru : en; }
