import { namespacedCopy, type Locale } from "./i18n.js";

const KEYS = [
  "expired",
  "history",
  "current",
  "closed",
  "closedNotice",
  "historyPartial",
  "historyLimited",
  "olderError",
  "conversation",
  "for",
  "close",
  "refresh",
  "loading",
  "empty",
  "readonly",
  "unavailable",
  "project",
  "task",
  "agent",
  "message",
  "send",
  "sending",
  "retrySend",
  "uncertain",
  "recordedNotice",
  "revision",
  "validation",
  "attach",
  "limits",
  "bytes",
  "size",
  "format",
  "count",
  "filename",
  "uploadRejected",
  "queuedUpload",
  "uploading",
  "ready",
  "uploadUncertain",
  "removing",
  "removeUncertain",
  "retry",
  "remove",
  "retryRemove",
  "download",
  "downloadError",
  "previewError",
  "recorded",
  "queued",
  "fetched",
  "acknowledged",
  "answered",
  "readConfirmed",
  "noRead",
  "operator",
  "unknown",
  "agentAuthor",
  "reply",
  "replying",
  "cancelReply",
  "earlier",
  "delivery",
  "deliveryProgress",
  "stepDone",
  "stepPending",
  "availabilityActive",
  "availabilityInactive",
  "availabilityUnknown",
  "prepareRun",
] as const;

export function conversationText(locale: Locale): { [K in (typeof KEYS)[number]]: string } {
  return namespacedCopy(locale, "conversation", KEYS);
}
