import { translate, type Locale, type MessageKey } from "./i18n.js";

const KEYS = [
  "suggested",
  "graph",
  "list",
  "graphHelp",
  "legend",
  "accepted",
  "completed",
  "review",
  "active",
  "ready",
  "queued",
  "blocked",
  "cancelled",
  "unknown",
  "unassigned",
  "noRun",
  "focus",
  "all",
  "graphLimit",
  "graphInvalid",
  "filtered",
  "edit",
  "addDependent",
  "cancel",
  "cancelHelp",
  "title",
  "description",
  "criteria",
  "dependencies",
  "noDependencies",
  "reason",
  "save",
  "add",
  "close",
  "working",
  "loading",
  "loadFailed",
  "refresh",
  "stale",
  "live",
  "unavailable",
  "readonly",
  "failed",
  "uncertain",
  "retry",
  "newAttempt",
  "success",
  "required",
  "cycle",
  "missing",
  "tooLarge",
  "cancelRequired",
  "selectedCount",
  "removeDependency",
  "keyboard",
  "cancelledDependency",
  "sourceChanged",
  "cancelConfirm",
  "draftKept",
] as const;

export type TaskGraphMessage = (typeof KEYS)[number];

export function taskGraphText(locale: Locale, key: TaskGraphMessage): string {
  return translate(locale, `task_graph.${key}` as MessageKey);
}
