"""Optional local delegation runtime.

The canonical ledger remains owned by :class:`CommonsManager`; this package
contains only operational launch state, bounded provider adapters, and
non-authoritative metadata telemetry.
"""

from .attempts import (
    ATTEMPT_SCHEMA,
    REQUEST_SCHEMA,
    Attempt,
    AttemptReason,
    AttemptReservation,
    AttemptSpec,
    AttemptState,
    AttemptStore,
    checkout_fingerprint,
)
from .broker import (
    BrokerLifecycleHook,
    BrokerRequest,
    BrokerResult,
    LocalBroker,
    NoopBrokerLifecycleHook,
)
from .diagnostics import (
    DiagnosticCode,
    SafeDiagnostic,
    classify_process_result,
    diagnostic_hint,
    diagnostic_safe_next_actions,
    error_safe_next_actions,
)
from .model import (
    BuiltinProfileId,
    ClaudePermissionMode,
    ClaudeRunnerProfile,
    CodexApprovalPolicy,
    CodexRunnerProfile,
    CodexSandbox,
    CorrelationIds,
    ProfileRegistry,
    Provider,
    RunnerInvocation,
    RunnerProfile,
    default_profile_registry,
    resolve_trusted_executable,
)
from .policy import OperatorLimits, PolicyViolationError, RuntimePolicy, RuntimeUsage
from .preflight import preflight_profile
from .subprocess_runner import (
    CancellationToken,
    ProcessFactory,
    ProcessGroupTerminator,
    ProcessHandle,
    ProcessResult,
    RunOutcome,
    RunReason,
    SafeEnvironment,
    SubprocessRunner,
)
from .telemetry import (
    JsonlTelemetrySink,
    NoopTelemetrySink,
    OpenTelemetrySink,
    TelemetryEvent,
    TelemetryKind,
    TelemetrySink,
)
from .tool_audit import (
    TERMINAL_TOOL_NAMES,
    TOOL_AUDIT_SCHEMA,
    TerminalToolAudit,
    TerminalToolAuditStore,
)

__all__ = [
    "ATTEMPT_SCHEMA",
    "REQUEST_SCHEMA",
    "Attempt",
    "AttemptReason",
    "AttemptReservation",
    "AttemptSpec",
    "AttemptState",
    "AttemptStore",
    "BrokerLifecycleHook",
    "BrokerRequest",
    "BrokerResult",
    "BuiltinProfileId",
    "CancellationToken",
    "ClaudePermissionMode",
    "ClaudeRunnerProfile",
    "CodexApprovalPolicy",
    "CodexRunnerProfile",
    "CodexSandbox",
    "CorrelationIds",
    "DiagnosticCode",
    "JsonlTelemetrySink",
    "LocalBroker",
    "NoopBrokerLifecycleHook",
    "NoopTelemetrySink",
    "OpenTelemetrySink",
    "OperatorLimits",
    "PolicyViolationError",
    "ProcessFactory",
    "ProcessGroupTerminator",
    "ProcessHandle",
    "ProcessResult",
    "ProfileRegistry",
    "Provider",
    "RunOutcome",
    "RunReason",
    "RunnerInvocation",
    "RunnerProfile",
    "RuntimePolicy",
    "RuntimeUsage",
    "SafeDiagnostic",
    "SafeEnvironment",
    "SubprocessRunner",
    "TelemetryEvent",
    "TelemetryKind",
    "TelemetrySink",
    "TERMINAL_TOOL_NAMES",
    "TOOL_AUDIT_SCHEMA",
    "TerminalToolAudit",
    "TerminalToolAuditStore",
    "checkout_fingerprint",
    "classify_process_result",
    "default_profile_registry",
    "diagnostic_hint",
    "diagnostic_safe_next_actions",
    "error_safe_next_actions",
    "preflight_profile",
    "resolve_trusted_executable",
]
